---
# yaml-language-server: $schema=https://raw.githubusercontent.com/docker/cli/master/cli/compose/schema/data/config_schema_v3.13.json
x-options: &options
  networks: [default]
  env_file: .env
  environment: &environment
    TZ: "${TIMEZONE:-America/Denver}"
  deploy: &deploy
    restart_policy:
      condition: unless-stopped

services:
  neo4j:
    <<: *options
    image: neo4j:5.26.0
    container_name: neo4j
    environment:
      <<: *environment
      NEO4J_AUTH: ${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-adminadmin}
      NEO4J_server_config_strict__validation_enabled: false
      NEO4J_server_memory_heap_initial__size: 512m
      NEO4J_server_memory_heap_max__size: 1G
      NEO4J_server_memory_pagecache_size: 512m
    volumes:
      - ./docker/data/neo4j:/data
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "http://localhost:7474"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - 62241:7474
      - 62242:7687

  graphiti:
    <<: *options
    image: zepai/knowledge-graph-mcp:latest
    container_name: graphiti
    depends_on: [neo4j]
    command: ["uv", "run", "graphiti_mcp_server.py", "--transport", "sse"]
    environment:
      <<: *environment
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: ${NEO4J_USER:-neo4j}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD:-adminadmin}
      # MODEL_NAME: ${MODEL_NAME}
      SEMAPHORE_LIMIT: ${SEMAPHORE_LIMIT:-10}
      GRAPHITI_TELEMETRY_ENABLED: false
    ports:
      - 62240:8000

  promptfoo:
    <<: *options
    image: ghcr.io/promptfoo/promptfoo:latest
    container_name: promptfoo
    environment:
      <<: *environment
      PROMPTFOO_SELF_HOSTED: true
    volumes:
      - ./docker/data/promptfoo:/home/promptfoo/.promptfoo
    ports:
      - 62243:3000
