[tools]
bun = "latest"
gh = "latest"
jq = "latest"
node = "lts"
task = "latest"
uv = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:task-master-ai" = "latest"
"npm:ccusage" = "latest"

[settings]
disable_backends = ["asdf", "pipx"]
pipx.uvx = true
npm.bun = true
experimental = true

[hooks]
enter = "mise i -q"
