[env]
_.python.venv = { path = ".venv", create = true }

[tools]
bun = "latest"
black = "latest"
gh = "latest"
jq = "latest"
node = "lts"
task = "latest"
uv = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:task-master-ai" = "latest"
"npm:ccusage" = "latest"

[settings]
disable_backends = ["asdf", "pipx"]
pipx.uvx = true
python.uv_venv_auto = true
npm.bun = true
