[env]
_.python.venv = { path = ".venv", create = true }

[tools]
bun = "latest"
claude = "latest"
dotenvx = "latest"
dprint = "latest"
gitleaks = "latest"
gh = "latest"
jq = "latest"
lefthook = "latest"
node = "lts"
ruff = "latest"
task = "latest"
uv = "latest"

[settings]
disable_backends = ["asdf", "pipx"]
pipx.uvx = true
python.uv_venv_auto = true
npm.bun = true

[hooks]
enter = "mise i -q"
