name: Publish

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile.claude
      - .github/workflows/publish-claude.yaml

env:
  DOCKER_USERNAME: brettinternet
  DOCKERFILE: Dockerfile.claude

jobs:
  build-and-publish-container:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skipci')"
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to the Docker registry
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Extract image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: latest=auto
          tags: type=ref,event=branch
          labels: |
            org.opencontainers.image.name=${{ github.event.repository.name }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}/tree/main
            org.opencontainers.image.description=Run Claude in a containerized sandbox.
            org.opencontainers.image.licenses=MIT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          platforms: arm64,amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_VERSION=${{ steps.meta.outputs.sha }}
            BUILD_DATE=${{ github.event.repository.updated_at }}
            BUILD_ENVIRONMENT=production

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
          repository: ${{ env.DOCKER_USERNAME }}/${{ github.event.repository.name }}
          short-description: Run Claude in a containerized sandbox.
          readme-filepath: README.md
